Load map file in non-strict mode
kartotherian/tilelive-vector pull request #3
Opened 2018-09-24 08:10 UTC by mdholloway

Needed to avoid errors with fonts.

Bug: https://phabricator.wikimedia.org/T195513

2018-09-24 15:16 UTC, nyurik approved these changes

2018-09-25 14:56 UTC, thesocialdev requested changes
Tests are failing locally, in master there are 27 fails and in your branch 28 fails, I am not sure what it can be but I think we should double check.

2018-09-26 05:01 UTC, mdholloway commented
Most of the failures are due to the requirement to set a MapboxAccessToken environment variable with an API token from Mapbox before running the tests.  This seems to be a new requirement since the tests were written.  (Actually, it's also an open issue upstream: https://github.com/mapbox/tilelive-vector/issues/153)

When I view my Mapbox account, it has a default public token that I think was auto-created when I created the account.  Setting it as the value of the MapboxAccessToken env var got these tests passing.  (Hopefully I won't be charged, still need to check...)

There are a couple of other tests failing due to an Amazon s3 auth failure somewhere, and these can be quieted by setting TILELIVE_VECTOR_NO_AUTH (see https://github.com/mapbox/tilelive-vector/pull/116).

With these environment variables set, all tests pass for me both before and after this change.  Can you verify?

2018-09-26 13:46 UTC, thesocialdev approved these changes

2018-09-26 13:46 UTC, merged